package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildFeature
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Eclipse'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Eclipse")) {
    params {
        add {
            param("a", "")
        }
    }

    vcs {
        remove(RelativeId("Eclipse"))
        add(RelativeId("Eclipse_2"))
    }

    features {
        val feature1 = find<BuildFeature> {
            feature {
                type = "splitTests"
                param("numberOfParts", "2")
            }
        }
        feature1.apply {
            enabled = false
        }
    }
}
