package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.TestsSplitFeature
import jetbrains.buildServer.configs.kotlin.buildFeatures.testsSplit
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Eclipse'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Eclipse")) {
    features {
        val feature1 = find<TestsSplitFeature> {
            testsSplit {
                numberOfParts = 2
            }
        }
        feature1.apply {
            enabled = false
        }
    }
}
