package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Er'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Er")) {
    expectSteps {
    }
    steps {
        insert(0) {
            maven {
                goals = "test"
            }
        }
    }
}
