package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.testsSplit
import jetbrains.buildServer.configs.kotlin.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'SplitedTests1'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("SplitedTests1")
    name = "splited tests1"

    vcs {
        root(RelativeId("Eclipse1"))
    }

    steps {
        maven {
            goals = "clean test"
            pomLocation = "java_eclipse/pom.xml"
            runnerArgs = "-Dmaven.test.failure.ignore=true"
        }
    }

    features {
        testsSplit {
            enabled = false
            numberOfParts = 2
        }
    }
}))

